### ISSUE TITLE
What is the equivalent of a repeating linear gradient in scenery?

### ISSUE THREAD

**Issue by notsiddhartha** [phetsims/bending-light#13]
I am trying to port the LightWaveNode to javascript. In the Java version, a cyclic GradientPaint is used for the alternating color pattern. What is the equivalent for this in Scenery?

**Comment by samreid** [comment]
@jonathanolson can you answer this?

**Comment by jonathanolson** [comment]
There's no way to directly do this using just LinearGradient. It will need to be transformed into an image and then used with Pattern.

**Comment by samreid** [comment]
Thanks @jonathanolson.  @notsiddhartha let us know if you have further questions.

**Comment by notsiddhartha** [comment]
Thanks @jonathanolson @samreid. Will try that. 

I see that SVG has spreadMethod=repeat for linearGradient, is the lack of similar support in Canvas the reason for using Pattern?

**Comment by jonathanolson** [comment]
Lack of support in Canvas is an obstacle since we use rendering to Canvas for screenshots in sims, and it would be fairly clunky to render it to Canvas nicely (would require including Canvg and working around a few issues, or writing our own support).

I'm not opposed to adding SVG-specific options to Scenery, however I doubt we'd want to use them in a simulation.

I'd like to hear @samreid's opinion, but I'd personally recommend the image conversion approach.

**Comment by samreid** [comment]
To answer @notsiddhartha's question: yes, we are using Pattern instead of SVG.spreadMethod=repeat so that it can be drawn in different renderers.

**Comment by notsiddhartha** [comment]
Thanks @samreid. Closing.
