### ISSUE TITLE
Add documentation for the webgl layout code

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#147]
During #44 I saw this code in the WebGL layout:

```js
heightOffset = ((window.innerHeight - (this.screenHeight + 40) * scale) / 2) + 40 * scale;
```

Can you please elaborate on what is happening here in a comment?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Thanks, this is much clearer.  My only question is about the navbar: I thought the webgl canvas was fitted to the area above the navbar, so I'm not sure why you have to subtract off the 40 here.  Is my assumption incorrect or is something else going on here?

**Comment by ChandrashekarBemagoni** [comment]
In sim.js (in resize() ) initially scale is taken with out considering the navigation bar.
 After finding the scale navigation bar height    is 
```var navBarHeight = scale * NavigationBar.NAVIGATION_BAR_SIZE.height;```

  Now the screen hight becomes 
 ``` var screenHeight = height - sim.navigationBar.height;```
  with this new screen height new scale is calculated in screenview(for each screen).

**Comment by samreid** [comment]
In the code, I tried setting `var navigationBarHeight = 0;` and did not see any differences.  Am I missing something?

**Comment by ChandrashekarBemagoni** [comment]
In fragment shader default origin is at lower left corner. So, any change in navigationBarHeight will change the Y1 position which is derived from gl_FragCoord and also changes the scaling. This can be observed in following figures there is a difference in wavelength and phase
![nvbh40](https://cloud.githubusercontent.com/assets/7919831/9422867/58af70c4-48c5-11e5-9a85-edea10673d35.png)
![nvbh0](https://cloud.githubusercontent.com/assets/7919831/9422868/58b1c950-48c5-11e5-9d3d-e62da13fd6c3.png)

**Comment by samreid** [comment]
I see, there are 13 wave crests in one picture and 12 in the other (for the incoming ray).  You can see how they are out of phase if you overlay them with partial transparency:

![image](https://cloud.githubusercontent.com/assets/679486/9444101/f7257000-4a41-11e5-9801-9cdfd44f8f28.png)

> In fragment shader default origin is at lower left corner.

My only concern is that I thought the default shader origin is at the lower left corner of the WebGL canvas.  Checking the element inspector, I see that the webgl canvas spans the screen (past the navbar):

![image](https://cloud.githubusercontent.com/assets/679486/9444204/8e50b6d8-4a42-11e5-875f-424f85a7c71e.png)

I need to look into this and see why it is so, perhaps may consult with @jonathanolson on this.

**Comment by jonathanolson** [comment]
WebGL blocks default to take up all available space, and since Scenery's display bounds include the navbar, the Canvas will extend over that region. It's expected to be that large.

**Comment by samreid** [comment]
So when do we need to subtract off the navbar height for webgl layout?

**Comment by samreid** [comment]
@jonathanolson can you discuss this with me soon, so we can determine whether any work remains for @ChandrashekarBemagoni?

**Comment by jonathanolson** [comment]
I'd like to propose an alternative way of rendering WaveWebGLNode:

It's possible to pass model coordinates of each vertex to the vertex shader, and set up a varying vec2 that will interpolate this for the fragment shader. Then you have access to the model coordinate directly in the fragment shader, instead of having to do lots of computation to determine the value.

This should remove the need to have any knowledge about layout, or the navigation bar that WaveWebGLNode currently requires.

**Comment by samreid** [comment]
@ChandrashekarBemagoni can you implement it as @jonathanolson described?

**Comment by ChandrashekarBemagoni** [comment]
Implemented. Assigning to @samreid for review

**Comment by samreid** [comment]
It appears as if the phase no longer matches properly at the interface after this change. It looks good at some window sizes but not others.  I found the issue below by gradually resizing the window.  @ChandrashekarBemagoni can you take a look?

![image](https://cloud.githubusercontent.com/assets/679486/9831445/4f454b0c-5915-11e5-9741-b423d3bd0ccf.png)

**Comment by samreid** [comment]
This phase issue was noticed again in https://github.com/phetsims/bending-light/issues/157#issuecomment-140119019

**Comment by ChandrashekarBemagoni** [comment]
​This phase issue is happening only in mac ,not on windows 7, iPad and did't check in windows 8.
this problem is due to varying vPosition (interpolated vertex) is not correctly interpolated.
This can be observed in following videos
Here directly using the value obtained vPosition

for x<388
        'if(vPosition.x<388.0){',
        'gl_FragColor = vec4(0.0,1.0,0.0,1.0);',
        '}',
        'else{',
        'gl_FragColor = vec4(0.0,0.0,1.0,1.0);',
        '}',
![s1](https://cloud.githubusercontent.com/assets/7919831/10537795/d3174036-7411-11e5-8907-a447055e01b8.gif)


This may be happening because of passing large values in vertex positions.The below video is by constraining all the points to the Rectangle( 0, 0, 1000, 1000 );
![s2](https://cloud.githubusercontent.com/assets/7919831/10537802/db45bbc0-7411-11e5-8a18-1d3acc6f8b9e.gif)

The other way is to just use the old code with all the computations made from nav bar and layout bounds

**Comment by samreid** [comment]
@ChandrashekarBemagoni thanks for demonstrating this problem.  In the above commit, I reduced the length of the transmitted ray.  It is still long enough to fit on the screen at extreme aspect ratios, but the webgl rendering artifact is no longer observed.  This issue is complete, thanks for your discovery!
