### ISSUE TITLE
Is there anything that should be generalized and migrated to common code?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#151]
From the review in #44, one of the items asks:

> Is there anything that should be generalized and migrated to common code?

I'm unfamiliar with the roadmap for our upcoming sims as well as the design of Optics Lab, which is under development.  @ariel-phet can you take a look at Bending Light and let me know if you recommend generalizing any of the components?  Particularly, the protractor and intensity meter, but if you see anything else, please let me know.

**Comment by samreid** [comment]
@ariel-phet can you comment on the above issue?

**Comment by ariel-phet** [comment]
@samreid - a protractor will likely be needed for some math sims...however, it probably makes more sense to generalize this element once we know the requirements of a protractor for math (for instance people might want a translucent/not translucent option). I do not think it makes sense to migrate this element to common code yet since we will not know the requirements until later.

The intensity meter should definitely be common code since it is used in this sim, and beers law lab. (and likely will appear in other sims).

Is the laser pointer generalized yet?

**Comment by samreid** [comment]
The laser pointer is a custom implementation (not generalized) and the intensity meter is also a custom implementation (not generalized).  I'll create an issue for the latter.  What other sims will need the LaserNode?

**Comment by ariel-phet** [comment]
We noticed that Beer's law lab uses the laser noded

**Comment by samreid** [comment]
I moved the outstanding issues to #202 and #203, closing this parent issue.
