### ISSUE TITLE
Add mipmaps

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#191]
@samreid please add mipmaps where appropriate (for instance the protractor)

**Comment by samreid** [comment]
Current problems I see on os x firefox:
![image](https://cloud.githubusercontent.com/assets/679486/9510149/bfb1ad42-4c25-11e5-808f-3b87bd3036ec.png)

![image](https://cloud.githubusercontent.com/assets/679486/9510153/c80c9272-4c25-11e5-9b45-d2375b1f8a96.png)

![image](https://cloud.githubusercontent.com/assets/679486/9510156/d1049bc2-4c25-11e5-958c-1c92fc4a4727.png)

Everything else is ultra-crisp.

**Comment by samreid** [comment]
Well, at different screen sizes, I also see:
![image](https://cloud.githubusercontent.com/assets/679486/9510217/5cbb04b2-4c26-11e5-8701-af10fff662fa.png)

**Comment by samreid** [comment]
Just changing image! to mipmap! I received this message:

> Uncaught Error: Assertion failed: Matrix has NaNs, non-finite values, or isn't a matrix!

**Comment by samreid** [comment]
Mipmap has saved the day once again, thanks @jonathanolson!

![image](https://cloud.githubusercontent.com/assets/679486/9510292/33863f20-4c27-11e5-8f28-f1ac961d8e19.png)

I can't easily or regularly make the laser image look awkward (even on the prisms screen, where it is a bit more prone), so I'm going to leave it alone unless/until I hear otherwise.
