### ISSUE TITLE
White light should have only 1 ray

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#192]
Assigning to @samreid as a question for @kathy-phet during status meeting

Advantages:

1. Performance
2. Reduction of clutter
3. Multiple rays of white light seems not particularly useful and too busy.

**Comment by samreid** [comment]
@kathy-phet and @phetsims/dubson agreed that we can get rid of the 5 white light rays.  @ariel-phet suggested getting rid of the 1 vs 5 ray radio buttons out of the play area and moving something simple into the control panel (white / 1 / 5) until we can have a designer take a closer look.

**Comment by samreid** [comment]
Here's a testable version for review:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.27/bending-light_en.html

It's at a good point now to get feedback from a designer about how the controls should work.  Some options:
Radio buttons to choose between white/single color rays.  Then for singe color rays, an on/off toggle  for 1 vs 5 rays.
Radio buttons to choose between white/1 ray/5 rays.

Plenty of ways to do this, those are just some options.  Please let me know your recommendation @arouinfar or @ariel-phet.

**Comment by arouinfar** [comment]
After the last design meeting, it was decided to use three pictorial radio button to depict monochromatic/single ray, monochromatic/multi ray, and white light. It was suggested to use a rainbow icon for white light, but that poses some challenges -- most notably, we cannot show a rainbow coming out of a laser. I've mocked up this option instead, which @ariel-phet has given general approval of.
![image](https://cloud.githubusercontent.com/assets/8419308/10114080/09bb237e-63a9-11e5-96cc-96248aeb4632.png)

What would you need to implement these @samreid? Do you need me to send individual assets for each button?

**Comment by kathy-phet** [comment]
Just to chime ... I like this much better than a rainbow, because you get to discover that is what happens.
K

Sent from my iPhone

On Sep 25, 2015, at 5:21 PM, Amy Rouinfar <notifications@github.com<mailto:notifications@github.com>> wrote:


After the last design meeting, it was decided to use three pictorial radio button to depict monochromatic/single ray, monochromatic/multi ray, and white light. It was suggested to use a rainbow icon for white light, but that poses some challenges -- most notably, we cannot show a rainbow coming out of a laser. I've mocked up this option instead, which @ariel-phet<https://github.com/ariel-phet> has given general approval of.
[image]<https://cloud.githubusercontent.com/assets/8419308/10114080/09bb237e-63a9-11e5-96cc-96248aeb4632.png>

What would you need to implement these @samreid<https://github.com/samreid>? Do you need me to send individual assets for each button?

-

**Comment by samreid** [comment]
@arouinfar these icons look great, and I have a few questions about them.  Why did you choose to have the inner rectangle in the white light icon and what do you think of removing it like so?

![out](https://cloud.githubusercontent.com/assets/679486/10121191/09a032fe-649d-11e5-811f-ebb749276b6b.png)

(Perhaps to make it easy to show it is highlighted by making the border bold?)

Also, I noticed you changed the ordering from white -> mono x1 -> mono x5 to mono x1-> mono x5 -> white.  Is this to encourage people to move to the "mono x5" after trying the "mono x1"?

**Comment by arouinfar** [comment]
@samreid thanks for mocking up this alternative. I originally preferred an all-black icon, but I had a few concerns. Namely,
* The stroke may not be visible
* When at a reduced opacity, the black will look gray (still a problem in the icons I proposed)
* It may not be possible to have scene selection buttons with different fills

If the third point is not really an issue, I'd like to go with what you've mocked up. To make the selected button more obvious, perhaps we can try a red stroke instead. Red will contrast against both the white and black buttons. 

As for the ordering, mono x1 is the default so it should be first. It seems most natural to keep the two monochromatic options together. If anyone on the design team has a strong pedagogical reason to swap mono x5 and white light, that'd be fine with me. But for now, it makes the most sense to keep the order mono x1, mono x5, white.

**Comment by samreid** [comment]
We should solve #252 before continuing on this issue.

**Comment by samreid** [comment]
Some commits in https://github.com/phetsims/bending-light/commit/40128db3222afd844ad5c81fef1e62038f9a7b16

**Comment by samreid** [comment]
> It may not be possible to have scene selection buttons with different fills

Indeed, it is much easier to have a rectangle inside the radio button rather than changing its entire fill.  

I've implemented the radio buttons as described (though please note there are some minor pixel differences in padding, etc.) and I've expanded the width of the radio button group to align with the control panels above and below (at least for English--will be different for different languages).

Current version looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/10194345/6217a7aa-6745-11e5-9855-a627f2084add.png)

@arouinfar any feedback on this version?  Would you like me to publish a dev version to review in context?

**Comment by ariel-phet** [comment]
I think this looks OK by the way

**Comment by samreid** [comment]
I published a dev version here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.31/bending-light_en.html

and remembered that @arouinfar said:

> To make the selected button more obvious, perhaps we can try a red stroke instead. Red will contrast against both the white and black buttons. It will also work against a black background -- something I hadn't thought of until just now.

so I'll try that next.

**Comment by samreid** [comment]
Red stroke looks good against the black background:
![image](https://cloud.githubusercontent.com/assets/679486/10197765/62124ef2-6756-11e5-913a-c222f707748b.png)

Not sure about against the white background--is there interference or synergy with the laser color?
![image](https://cloud.githubusercontent.com/assets/679486/10197799/825807e2-6756-11e5-9e4b-ad5b386b229a.png)

**Comment by arouinfar** [comment]
As discussed with @kathy-phet and @samreid the active stroke will be blue.

**Comment by samreid** [comment]
Fixed above, closing.
