### ISSUE TITLE
Total output of laser looks like it is not conserved

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#246]
In this screenshot, observe the amount of light coming out of the laser (immediately in front of the laser), then consider the total amount of light reflected and refracted across the screen.  It seems like more light was created--that reflecting and refracting is somehow increasing the total amount of light coming out of the laser.  

For instance, the 5 rays exiting the right side of the screen are *nearly* as bright as the 5 rays emanating from the laser, yet there are many reflected/refracted rays (not all of which are dim).  It seems like they don't add up to the same total.

@ariel-phet do you think this will deceive students or teachers?

![image](https://cloud.githubusercontent.com/assets/679486/10101157/0ac52026-6354-11e5-92c7-39473866d338.png)

**Comment by ariel-phet** [comment]
@samreid can you give me any insight as to the model? Usually standard reflection off glass is around 4 percent. Do we have some attenuation built into the model when going through material?

Perception of brightness is also a fairly complicated phenomenon....you perceive different colors of the same intensity to be different brightness, and usually a laser starts out above the saturation intensity of your eye's dynamic range. I don't necessarily see a problem, but might be nice for me to understand the model a bit better.

**Comment by samreid** [comment]
There is no attenuation at the surfaces or in the vacuum, power_in = power_reflected + power_refracted.   I think you addressed the point when you said:

> usually a laser starts out above the saturation intensity of your eye's dynamic range

Even though this is true, will it still be confusing for teachers or students, where it *looks* like power_reflected+power_refracted > power_in ?

**Comment by ariel-phet** [comment]
@samreid I don't think so...this behavior matches the java version which is quite popular, and I know of no complaints/issues. 

The only way to address this issue is to make the model more accurate and add some attenuation. I think for most of the use cases that is not really necessary. One thing we can make sure to do is make a note in the teacher tips, but I would not worry about altering the model at this point (the only "real" way to do that would be do add a exponential decay function that depends on material thickness) I suppose such a model exists in Beer's law lab, but it seems like unnecessary complexity here when the focus is on reflection and refraction.

**Comment by samreid** [comment]
Documented in model.md and closed.
