### ISSUE TITLE
The laser looks a bit aliased

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#253]
From #240 @arouinfar said:

> The laser also looks a bit aliased. Is it being drawn in code or is it an image @samreid?

**Comment by samreid** [comment]
It is a (small-ish) image: 
https://github.com/phetsims/bending-light/blob/29249c814a7eeb04b48d1f5cdbee7216e698fed3/images/laser.png

But I also noticed it is not mipmapped.

What platforms/window sizes did you see an issue with?  If I can see the same problem I can try mipmapping.  If that doesn't help, we could try mipmap+ higher resolution source image.

**Comment by arouinfar** [comment]
The laser looks fine on my Mac. It was pretty aliased looking on the iPad2 (beyond typical fuzziness of the non-retina display).

**Comment by samreid** [comment]
Can you share a screenshot?  I have no iPad2 and not sure what combination of larger image/mipmapping will help.

**Comment by samreid** [comment]
Switching to mipmap! works ok on desktop, but on iPad3 I'm getting a blank screen display.  Homescreen is OK, screen screen is not.

**Comment by arouinfar** [comment]
@samreid The laser looks great on the iPad3. I don't know what you mean by 
 >Homescreen is OK, screen screen is not.

I'm not noticing any issues in the latest pull.

**Comment by arouinfar** [comment]
The laser still looks a bit aliased on the iPad2, but does look somewhat better. From the latest pull:
![image](https://cloud.githubusercontent.com/assets/8419308/10676018/8688e4d2-78c0-11e5-9a1f-5ffdb230ae18.png)
![image 2](https://cloud.githubusercontent.com/assets/8419308/10676017/868889ba-78c0-11e5-8713-33c40106071b.png)
I think this might be as good as it will get for the iPad2. I'm fine with closing the issue @samreid, but I'll leave it open because I'm not sure about your comment regarding the iPad3.

**Comment by samreid** [comment]
>>  Homescreen is OK, screen screen is not.

> I'm not noticing any issues in the latest pull.

I didn't push my investigative changes with mipmapping the laser since it was preventing the sim from rendering in some cases, for unknown reasons.

I don't know if mipmapping will help that image at all on iPad2, perhaps we can close the issue for now and re-evaluate if we get complaints.
