### ISSUE TITLE
Layouts have some extra space when strings are doubled

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#304]
In the index of refraction control panels, with ?stringTest=double there is some extra whitespace on the right for some of the controls.  Everything is still legible.

![image](https://cloud.githubusercontent.com/assets/679486/11259106/1542a738-8e1c-11e5-9b2d-94e6503b21e7.png)

Should we spend time to understand what is happening here and try to solve it?

**Comment by samreid** [comment]
Discovered during #301

**Comment by samreid** [comment]
I don't think we should try to dynamically adjust the size of the combo box to fit the width, but we could right align them if desired.  @ariel-phet can you decide?

**Comment by ariel-phet** [comment]
I think fine to leave as is.

Left alignment makes most sense in this case because it puts the name of the material next to "material" the label.

However, the combo box seems to have way more white space than necessary, not a huge deal, but the combo box is actually really large horizontally *without* stringTest=double and actually shrinks to a more reasonable size *with* stringTest=double

![nostringtest](https://cloud.githubusercontent.com/assets/4051174/11264201/e811f754-8e4e-11e5-9a53-e624056e5513.PNG)
![stringtest](https://cloud.githubusercontent.com/assets/4051174/11264200/e811430e-8e4e-11e5-9fa6-b2f8daee5d44.PNG)

**Comment by ariel-phet** [comment]
@samreid Mind giving some insight as to what is causing the two different sizes of the combo box? The size with no string test is large, but its alignment is aesthetically pleasing. The smaller size leaves some odd trapped space in the upper right hand corner.

**Comment by samreid** [comment]
New version is here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.44/bending-light_en.html

@ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
looking good, closing.
