### ISSUE TITLE
inconsistent UI for manipulating laser

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#317]
Noted while working on https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2.

When the laser is can be both rotated and translated, it's image has a knob, as shown below. The laser is rotated by dragging the knob, translated by dragging the body.

![screenshot_102](https://cloud.githubusercontent.com/assets/3046552/11406803/711826e6-936c-11e5-8c94-56eeff8292eb.png)

When the laser can only be rotated, it's image has no knob, as shown below. The laser is rotated by grabbing the body -- which is entire different than the above case.  This seems very odd - shouldn't the affordance used to translate disappear, rather than changing the semantics of the "knob" affordance?  I suspect that it's not confusing users only because of the arrows that appear to indicate how the laser can be manipulated.

![screenshot_103](https://cloud.githubusercontent.com/assets/3046552/11406801/6e43adbe-936c-11e5-83ab-dfa4ade6b701.png)

**Comment by ariel-phet** [comment]
Interesting point @pixelzoom 

Actually, I never gave it too much thought but on the "prism" screen when the laser is able to rotate, wouldn't it feel more natural to rotate about its own center, rather than what feels like an arbitrary point on that screen. I am guessing @samreid did this since the rotation then was a similar implementation on all 3 screens, but I am not sure if it is the best user experience.

**Comment by arouinfar** [comment]
> When the laser can only be rotated, it's image has no knob, as shown below. The laser is rotated by grabbing the body -- which is entire different than the above case. This seems very odd

This behavior matches the original Java version, but now that I think about it, it does seem a bit odd. I think it would make sense to add the knob to the laser in the Intro and More Tools screens to keep a consistent UI.

> on the "prism" screen when the laser is able to rotate, wouldn't it feel more natural to rotate about its own center

I agree with @ariel-phet, that this may be a more natural-feeling rotation. However, I like that rotation is consistent across all three screens. I'd also be worried that the rotation would become too sensitive on touch devices if the pivot was moved to the laser's center.

**Comment by samreid** [comment]
I don't think it matters much one way or another in terms of usability--both modes (rotate about arbitrary point/rotate about center) seem equally acceptable, but I do see @arouinfar's point about sensitivity on touch devices.  

Regarding the other point @pixelzoom raised: I don't think the laser on screens 1 and 3 need a knob since there is only one way to interact with the laser--a knob there would seem like an unnecessary artifact taking up screen space.  The knob is necessary on the prisms screen so the laser can be translated or dragged.  In my opinion, consistency doesn't seem to be the most important concern in this case.

@arouinfar and @ariel-phet it seems like this issue needs further discussion before work begins.

**Comment by ariel-phet** [comment]
@samreid - can you give me an estimate of what it would take to make the laser rotate about its center on the prisms screen? If it is an easy change I would like to try it out on a touch device and see how it feels.

**Comment by samreid** [comment]
I showed a prototype where the laser rotates about its tip, and @ariel-phet and @arouinfar thought it looked good.

**Comment by samreid** [comment]
Fixed above, should be published for review.

**Comment by samreid** [comment]
@ariel-phet tested this on iPad2 and reported it is good.
