### ISSUE TITLE
Slow performance with "Wave" setting selected on Safari 9.0

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#318]
Test device: Personal Mac
Operating System: 10.11
Browser: Safari 9 
Problem description: "Slow performance when the laser has the "Wave" setting selected on the Intro and More Tools" screens. In particular the sim lags when attempting to move the tools, i.e protractor and intensity measurement device. The objects don't move with the mouse immediately. 

Steps to reproduce:

Severity: Low

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.45/bending-light_en.html
Version: 1.0.0-dev.45 2015-11-20 05:48:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"e67f1f6a","branch":"master"},"bending-light":{"sha":"51676950","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"a4994516","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"joist":{"sha":"446cc8e8","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d9d2e688","branch":"master"},"scenery":{"sha":"a4a93afb","branch":"master"},"scenery-phet":{"sha":"5a6969fe","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"7b4a98d6","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"}}

**Comment by orejolaphet** [comment]
Note: on the same computer the performance does not lag on Chrome 46

**Comment by samreid** [comment]
@ariel-phet do you want to spend time on this before the next dev version or RC?

**Comment by ariel-phet** [comment]
@samreid can you investigate? It seems odd to me this sim would perform so well on other desktop browsers and have an issue in safari. Do you see the slowness on your macbook air?

**Comment by samreid** [comment]
Things are pretty snappy on my mid-2012 macbook air, with both webgl=true and webgl=false.  Here's a movie with webgl (webgl=false looks the same speed):

![speed](https://cloud.githubusercontent.com/assets/679486/11550992/31f84d3a-9932-11e5-9f47-41ace1170cc3.gif)

I'm on OS X 10.11.1 and Safari 9.0.1.  To investigate further, the next steps would be:

1. for @orejolaphet to create a screen capture so that we can quantify the extent of the problem
2. for @orejolaphet to identify whether webgl was used or not (we could see this in the screen capture)
3. for @orejolaphet to reboot his machine and try again, in case the CPU was being capped by some other process.

Reassigning to @ariel-phet to decide how to proceed, please reassign to @orejolaphet if desired.

**Comment by ariel-phet** [comment]
@orejolaphet I am a bit suspicious that this might be device specific, so mind trying the steps above?

**Comment by orejolaphet** [comment]
I suspect it was my CPU. I restarted my computer and closed all other applications besides safari, and now everything runs pretty smooth on Safari 9.

**Comment by samreid** [comment]
Thanks for testing this @orejolaphet, seems like we can close this issue.
