### ISSUE TITLE
Inconsistency when measuring intensity in "Wave" vs "Ray" setting.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#319]
I noticed that between the two laser settings: "Wave" and "Ray", the intensity will not be measured for the "Ray" setting but will be measured for "Wave". 

Should the behavior be same for both settings?
Here is a screen shot of the "Wave" being measured
<img width="343" alt="screen shot 2015-11-30 at 8 18 25 am" src="https://cloud.githubusercontent.com/assets/5631059/11475604/836b01ce-973b-11e5-836e-b6bd4cb09e2e.png">

With out moving the location of the laser, only changing the setting to "Ray", we have
<img width="362" alt="screen shot 2015-11-30 at 8 18 13 am" src="https://cloud.githubusercontent.com/assets/5631059/11475610/876a179c-973b-11e5-903b-78e385ce3515.png">
Notice the laser ray passes through the lens, but intensity not measured.

**Comment by samreid** [comment]
I think the solution to this problem will be to fix the capture radius of the probe to match the graphical look--then the discrepancy will have an obvious physical reason.

**Comment by samreid** [comment]
I'm recalling a reason a smaller hit area on the sensor is better--a larger hit area accentuates the discontinuity in the light ray hitting the sensor near the origin.  Still, I think I should make the entire sensor region on the probe capture light, and then if the discontinuity is too distracting, then it should be fixed with math (though I think I am the only one that has noticed the discontinuity until now).

**Comment by samreid** [comment]
OK I matched the regions in the above commit.  Here's a screencast with the new behavior and the corner cases/discontinuities I am aware of:

![bendinglight](https://cloud.githubusercontent.com/assets/679486/11550376/cf977bd4-992c-11e5-81d9-922759d3996f.gif)

The other solution I considered would be to make the wave hit area match the ray hit area, so that a wave would only intersect if the ray would have.  @ariel-phet can you review everything in this issue and advise?

**Comment by ariel-phet** [comment]
The behavior in the comment above seems fine. Closing
