### ISSUE TITLE
stringTest=long disconnects wire from intensity meter body

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#331]
stringTest=long shows some odd behavior for the intensity meter (the wire disconnects from the meter body).

May not need to fix, but it does appear to happen with anything that goes above the stringTest=double.

![capture](https://cloud.githubusercontent.com/assets/4051174/11911637/576cf72e-a5d9-11e5-905e-9dfaa6c1b660.PNG)

@samreid should investigate to see if this is an easy fix

**Comment by samreid** [comment]
It looks like part of the intensity meter layout is using the width of the intensity meter body, and the width is being augmented by the numeric readout.  Since the strings should appear like so:

![image](https://cloud.githubusercontent.com/assets/679486/11959861/e65c8408-a88c-11e5-96db-5dc15ed34f3f.png)

or 
![image](https://cloud.githubusercontent.com/assets/679486/11959869/ef2cd808-a88c-11e5-93db-217b97e79487.png)

This will not be a problem unless translators substitute a much longer symbol for `%` or `-`.  I tried adding the Belarusian translation for "percent" and it looked like this:

![image](https://cloud.githubusercontent.com/assets/679486/11959991/a0f1be1e-a88d-11e5-8183-99cefdebc82e.png)

Since we do permit translation of this symbol, perhaps I should add a max width to this text.

**Comment by samreid** [comment]
Putting maxWidth to be 85% of the width of the white panel, it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/11960138/5c078a76-a88e-11e5-80c1-48d9a29a9a10.png)

With the English case still looking good:

![image](https://cloud.githubusercontent.com/assets/679486/11960113/2decfacc-a88e-11e5-9fac-14a98c084310.png)

This is a non-invasive change and will not require significant re-testing (just a spot test on 1 platform), so I'll go ahead and commit it to master and the 1.0 branch.

**Comment by samreid** [comment]
I've made this commit in the 1.0 branch and merged to master.  I'll mark this for "Needs Spot Test" in the next RC.

**Comment by arouinfar** [comment]
Looks good! Closing.
