### ISSUE TITLE
Fuzziness in iFrame

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#332]
Test device: iPad 2, Witten

Operating System: iOS 9.2 (13C75)

Browser: Safari

Problem description: there is a noticeable amount of fuzziness when the sim is loaded in the iFrame. Most prominent in the intro screen. 

Steps to reproduce: Opem sim in iFrame

Severity: minor

Screenshots:
![image](https://cloud.githubusercontent.com/assets/12610678/11937315/cd31b42e-a7d0-11e5-8172-07c5e601597b.png)

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-rc.1/bending-light_en.html
Version: 1.0.0-rc.1 2015-12-18 17:54:28 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"60075be9","branch":"HEAD"},"babel":{"sha":"dd59a2a4","branch":"master"},"bending-light":{"sha":"79a6385f","branch":"HEAD"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"d18a2538","branch":"HEAD"},"dot":{"sha":"24f07fa0","branch":"HEAD"},"joist":{"sha":"f73eef15","branch":"HEAD"},"kite":{"sha":"a4907ccc","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"98ea2eeb","branch":"HEAD"},"scenery-phet":{"sha":"a62aafce","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"1b39dfc5","branch":"HEAD"},"tandem":{"sha":"87f3d2ab","branch":"HEAD"}}

**Comment by samreid** [comment]
The same problem does not appear on OS X Safari:

![image](https://cloud.githubusercontent.com/assets/679486/11962362/82bf40b0-a89c-11e5-96e9-36681edcf199.png)

**Comment by samreid** [comment]
The problem does not occur on retina ipad (testing iPad3) iOS 9.2:

![ipad3](https://cloud.githubusercontent.com/assets/679486/11962451/22dfd276-a89d-11e5-8f77-463728b9c249.png)

We previously investigated the fuzzy iPad2 laser in this issue https://github.com/phetsims/bending-light/issues/253 but decided the issue wasn't too problematic.  The WebGL jaggedness for the web view seems tricky to solve and I have not investigated it.

Since this report indicated severity "minor" and the fixes seem like trouble, I'll close this issue.  We can re-open if we are getting lots of reports from clients having this issue on iPad2.
