### ISSUE TITLE
Laser boundaries for ray vs wave are not consistent with one another

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#56]
I noticed that the laser can be tilted fully horizontally when ray is selected while the laser will not reach its full horizontal position when in wave mode

Ray
![bendinglightscreenshot5](https://cloud.githubusercontent.com/assets/7717368/7918189/cb3aa276-084c-11e5-89f7-907e754100c6.png)

Wave
![bendinglightscreenshot6](https://cloud.githubusercontent.com/assets/7717368/7918195/d0ae0e96-084c-11e5-86b7-78415b4a2bed.png)

**Comment by arouinfar** [comment]
This behavior is also present in the Java sim. In wave mode the beam is much thicker. I think it would be problematic to allow the beam to sit so that half of it was above the surface and half of it below, which is what would happen if the laser was allowed to be fully horizontal. This situation is also not something that is addressed by the learning goals, so I think this behavior is fine as is. Good observation, @bryo5363.
