### ISSUE TITLE
Prisms screen performance is abysmal

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#6]
Tested on Windows 8 on Chrome 

The sim becomes unusable after adding a few objects for the light to be refracted off, turning on settings i,e:
show normal
white light
show reflections
multiply rays

Performance becomes extremely poor and any interaction takes a minute for any response to be shown.
.

**Comment by phet-steele** [comment]
Performance is still in issue in 1.0.0-dev.3 as per #53

**Comment by samreid** [comment]
I am getting 1474 ms/frame on my OS X Chrome, which is normally very speedy.  This is 0.7 frames per second and unusable.

**Comment by samreid** [comment]
@ariel-phet suggested that we could reduce from 5 to 3 rays when using white light.

@samreid asked if the radio button icon should change, and @ariel-phet said no.

**Comment by samreid** [comment]
This is mostly covered in other issues, so I'm going to unassign it.  Still, to remind me to look into it after other work is done, I'm going to leave this issue open.

**Comment by samreid** [comment]
This sim has come a long way since this issue was created.  The prisms screen is computationally and graphically demanding and we will have to decide what is acceptable.  It has recently been approved for iPad2, still a bit sluggish on Firefox.  I'm going to close this issue and if it seems too slow during dev testing or RC testing we can reopen.
