### ISSUE TITLE
Should Environment, Object, and Material drop down menus match the slider location?

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#64]
For these options 
![screen shot 2015-06-02 at 11 08 50 am](https://cloud.githubusercontent.com/assets/5631059/7941963/08783696-0918-11e5-91a5-0a12bd02251e.png)
![screen shot 2015-06-02 at 11 08 54 am](https://cloud.githubusercontent.com/assets/5631059/7941964/09be3438-0918-11e5-9419-35b8621161a9.png)
![screen shot 2015-06-02 at 11 08 36 am](https://cloud.githubusercontent.com/assets/5631059/7941966/0abc0be4-0918-11e5-9f36-9cd60582876d.png)

Should the drop down menus match the location of the slider when the slider is manuplated?

For example the Environment menu:
I manipulated the slider and brought it to it's minimum, but the drop down menu says "custom" rather than "air".
![screen shot 2015-06-02 at 11 09 44 am](https://cloud.githubusercontent.com/assets/5631059/7941981/23584014-0918-11e5-969c-42563044e1f0.png)

**Comment by arouinfar** [comment]
Good observation, @orejolaphet. This behavior is intentional and consistent with the Java sim. The drop down menu will always display "Custom" if the slider and/or tweakers are used to change the index of refraction (even if located at Air, etc.). We thought it would be distracting to have the drop down menu change its display while sliding through the values of the drop-down menu options.
