### ISSUE TITLE
Environment combo box opens outside of dev

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#70]
On the Prisms screen, the Objects drop down menu opens out of the dev boundary. 
![image](https://cloud.githubusercontent.com/assets/8419308/7966864/012516c6-09e4-11e5-89a7-2947e547ca95.png)

This issue is also present in the Java version.  The menu opens outside of the window:
![image](https://cloud.githubusercontent.com/assets/8419308/7966884/204c0bea-09e4-11e5-8972-a9ed360c6d21.png)

This menu should be changed to a drop "up" menu, like the one in Beer's Law Lab. We should probably be handling this issue internally, since we did not specify this in the mockups and the behavior exists in Java.

**Comment by samreid** [comment]
Fixed in this version:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.6/bending-light_en.html

@arouinfar there is currently one implementation for these combo boxes and I just changed the setting in one place and hence all of the combo boxes open "up" instead of down now.  This increases consistency between the 1st and 2nd screens, but I wasn't sure if we should take the extra step of making screen 1 and 3 boxes open up and screen 2 boxes open down.  Please review and comment.

**Comment by arouinfar** [comment]
Thanks @samreid! Having all combo boxes open up looks good to me. Closing.

**Comment by arouinfar** [comment]
Reopening this issue, as I've just noticed some problematic behavior. Now that all combo boxes open up, the Environment menu on the Prisms screen opens out of the dev boundary. Can you make this combo box be a drop down, @samreid? All other combo boxes can continue to drop "up".

**Comment by samreid** [comment]
Fixed in http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.10/bending-light_en.html
 please review.

**Comment by arouinfar** [comment]
Looks good, closing.
