### ISSUE TITLE
Prisms can be lost behind the panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#71]
On the prisms screen, it is possible to drag prisms behind the panels and lose them.

Dragging a prism behind the panel (but not yet hiding):
![image](https://cloud.githubusercontent.com/assets/8419308/7965126/c335b2e0-09d8-11e5-8ef3-ab1a3f262142.png)
In the screenshot below, the prism has been dragged completely behind the panel, but a lens has been dragged into the playspace. If you are unaware that there is a prism hiding behind the panel the beam path looks incorrect. The hiding prism is also now unretrievable.
![image](https://cloud.githubusercontent.com/assets/8419308/7965232/6d7cec1e-09d9-11e5-8128-e6d430c5f3b5.png)

If we decide to layer prisms above the panel, the beams should also be layered above the panel. From an aesthetic and usability standpoint, we do not want the laser beams to layer above the panels because it can get quite messy with more complicated arrangements.

Would it be possible/feasible to have the prism pop out from behind the panel enough to reveal a corner/edge if it is placed completely behind a panel? For example, in the situation described above, the prism was dragged so that it was completely hidden by the panel. Upon release, it would snap back to reveal a sliver of the prism that could be grabbed:
![image](https://cloud.githubusercontent.com/assets/8419308/7965341/1c399e96-09da-11e5-9221-37e5d29975fb.png)

@ariel-phet, can you please reassign this to the appropriate developer to handle this question?

**Comment by samreid** [comment]
Just revealing a tiny part of the edge doesn't seem sufficient.  I would recommend having 30+ pixels pop out to the side of the control panel, so it is clear what is happening and easy to grab.

**Comment by samreid** [comment]
In the above commit, I added the following rule:

if the center of the laser or prism is dropped behind the enviornment control panel or laser control panel (on the prism screen), then translate it to the left until its center is no longer obscured.  

This does permit corner cases like the following, but that may be acceptable since you can still see and grab the object.
![image](https://cloud.githubusercontent.com/assets/679486/9334865/32a20a34-458e-11e5-8535-852f0dc74bf9.png)

I'll publish a dev version shortly for @arouinfar to review.  Note that the laser is still in front of the control panels at the moment, but it will be bumped to the left nonetheless.

**Comment by samreid** [comment]
Also, here is a "worst case scenario" for releasing the prism shapes:

![image](https://cloud.githubusercontent.com/assets/679486/9335013/f759913a-458e-11e5-9702-58c17974f149.png)

@arouinfar can you review http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.8/bending-light_en.html and let me know if it is sufficient, or if you would recommend a change in the rules for handling occlusion?

**Comment by arouinfar** [comment]
This looks good to me @samreid. I was always able to retrieve the prisms, even in the edge cases you pointed out. I'll go ahead and close this issue. Thanks!
