### ISSUE TITLE
Why is there the option for protractor enlargement on one tab but not the other?

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#77]
Why does the user have the option to enlarge the protractor in 'More Tools' but not in intro?

**Comment by bryo5363** [comment]
Also why is there a button to access the protractor on Prisms but not on any other sim tab?

**Comment by arouinfar** [comment]
These features all match the original Java sim. The More Tools screen is meant to serve as a laboratory with additional features. The larger protractor facilitates easier/more precise measurement of the angle, which is less important on earlier screens. The protractor is the only tool available on the Prisms screen so it was given a checkbox rather than its own toolbox. This also leaves more room available for the play space.
