### ISSUE TITLE
Down arrow shouldn't be displayed when "wave" light at minimum location?

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#78]
I was just curious as the "ray" light (on the intro screen) does not display a lowering arrow when the light is located at its minimum.
![screen shot 2015-06-08 at 10 29 40 am](https://cloud.githubusercontent.com/assets/5631059/8039867/bf35c1d6-0dc9-11e5-9266-d5502bb0a47e.png)
But this behavior does not occur for the "wave" light. Should the two be consistent?
![screen shot 2015-06-08 at 10 28 54 am](https://cloud.githubusercontent.com/assets/5631059/8039920/14e17ab2-0dca-11e5-937d-f2d4b031e772.png)

**Comment by arouinfar** [comment]
Great observation, @orejolaphet! I agree that the lower arrow should not be present when the laser is at its minimum position in Wave mode. The current behavior matches the Java sim, so we should handle this internally.

**Comment by samreid** [comment]
Fixed above.  The only corner case I can think of is if using multitouch on a touch device and holding the laser while tapping on the "wave" radio button--it wouldn't hide the arrow in this case.  Hm... I actually tested this on iPad and it worked properly.  Oh, this is because the angle gets changed so the function gets re-evaluated.  That's perfect.  Closing.
